### ISSUE TITLE
sessionId无法匹配到，导致查询redis数据库是发现并没有数据写入

### ISSUE THREAD

**Issue by wangtianyang** [shoutrain/gMaxLinked#1]
在使用gMaxLinked时遇到如下问题：
    启动Redis Server，运行gMaxLinked能够正常连接Redis数据库并等待Client 连接。当我运行所提供的c测试client时，需要两个命令行参数，
分别为SessionId和groupId,于是我随便输入了SessionId(值：A1B2C3D4A1B2C3D4)，groupId(值：1)，连接到server成功后，gMaxLinked
输出信息如下：
![image](https://cloud.githubusercontent.com/assets/2756941/19545762/a26fdfb0-96bb-11e6-9e8e-f956b7e3e4a1.png)

client端输出信息如下：

![image](https://cloud.githubusercontent.com/assets/2756941/19545783/cdad1062-96bb-11e6-8537-4edbdafaaca3.png)

貌似是sessionId无法匹配到，导致查询redis数据库是发现并没有数据写入！不知道sessionId和groupid是否有什么特殊要求。

**Comment by shoutrain** [comment]
在客户端连接gMaxLinked的时候，要经历如下状态：
1. 连接，就是客户端connect，服务器端accept
2. tcp 连接建立后，如果在规定时间（可以配置）没有发送握手消息，那么连接就会被切断
3. 握手消息应该包括客户端版本号（方便服务器端检查是否是匹配的版本）、协议版本号、SessionID等字段
4. sessionId是唯一表示每个连接的ID，gMaxLinked会在Redis里面查找是否有这么一个Session，如果没有，就会切断连接。
5. 在session认真后，就会用心跳包维持连接，其他的业务包也会要求规定时间返回，凡出现预定的包规定时间内没有返回，就会切断连接。

你上面描述的问题，在于redis上没有建立session，这个session建议在redis里是一个hashes.

**Comment by baosongliang** [comment]
在收发协议帧的时候，是否未考虑字节序问题？

**Comment by shoutrain** [comment]
如果使用gMaxLinked的业务层，以及使用对应的客户端框架，那么不需要考虑，底层已经处理好了（特别是你在Java客户端示例中可以看到，有专门负责处理字节序的代码）。如果自己写客户端，那就需要根据不同语言自己处理了。@baosongliang
